
#define WIRE Wire

#define TOUCH_PIN 35
#define BUILTIN_LED 2





#define EYEBORDER 5




#define TOUCH_TOP_LOST_INTERVAL_MS 2000
#define TOUCH_LONG_PRESS_INTERVAL_MS 1000
#define TOUCH_LONG_PRESS_INTERVAL_END_MS 1800

#define BORING_INTERVAL_MS 40000
#define VERY_BORING_INTERVAL_MS 65000
#define LOST_ATTN_INTERVAL_MS 80000
#define GO_LOW_POW_INTERVAL_MS 180000
//for debug
// #define BORING_INTERVAL_MS 7000 
// #define VERY_BORING_INTERVAL_MS 9000 
// #define LOST_ATTN_INTERVAL_MS 15000 
// #define GO_LOW_POW_INTERVAL_MS 18000


// DISPLAY
#define LCD_DC 14
// #define LCD_CS 25 
#define LCD_SCK 25
#define LCD_MOSI 26
#define LCD_RST 27
#define LCD_BL 12
#define LCD_WIDTH 240
#define LCD_HEIGHT 240


#define LED_PHILAMENT_LEFT_PIN 22
#define LED_PHILAMENT_RIGHT_PIN 23
#define MAX_PHILAMENT_BRGIHT 60

// #define AUDIO_ON 1
// #define MOVE_ON 1
// #define SLEEP_ON 1
// #define WIFI_ON 0
// #define DEEP_SLEEP_ON 1